aws_eks_cluster             = "my-eks-cluster"
aws_region                  = "ap-south-1"
node_instance_type          = "t3.medium"
node_group_name             = "node-testing"
subnet_ids                  = ["", ""]
security_group_ids          = [""]
node_group_desired_capacity = 1
node_group_min_size         = 1
node_group_max_size         = 5
kubernetes_namespace        = "testing"
